KIF with SwiftUI
Karumi/KataSuperHeroesSwiftUI pull request #1
Opened 2020-03-09 15:54 UTC by davideme

![ezgif com-optimize](https://user-images.githubusercontent.com/858090/76232179-a08b8980-6226-11ea-9596-86ae592bc76c.gif)

- Add Support for SwiftUI
  - SuperHeroDetail View and ViewModel
  - SuperHeroesList View and SuperHeroesViewModel ViewModel
  - SuperHeroRow View
  - Use SDWebImageSwiftUI
  - Map LoadingView to as representable to SwiftUI
  - Update ServiceLocator 
  - Add support for Identifiable to SuperHero to be iterable for list

- Add support for catalyst, same code for iPad and Mac

- Use color in XCAssets

Cleanup:
- Remove storyboards, ViewControllers, Cells, Datasource, Delegate and presenters.

Pending next PR:
- Update Readme and Exercise branch

2020-03-09 16:33 UTC, untalfranfernandez approved these changes

2020-03-10 10:16 UTC, pedrovgs requested changes

2020-03-10 10:16 UTC, pedrovgs commented on KataSuperHeroes/SuperHeroesList.swift
> +let superHeroData = [
Couldn't we reuse the hardcoded data we've declared in the repository?

2020-03-10 10:16 UTC, pedrovgs commented on KataSuperHeroesTests/SuperHeroesViewControllerTests.swift
> -    }
This test was added to ensure the table view does not show more items than super heroes are. I understand now this makes no sense, but I'm wondering if there is any alternative with SwiftUI to check if a view has n items.

2020-03-10 10:16 UTC, pedrovgs commented on KataSuperHeroesTests/SuperHeroesViewControllerTests.swift
> +        tester().waitForAbsenceOfView(withAccessibilityLabel: "Superhero name")
Shouldn't we check the name of the superhero is being shown on the screen? I know the previous tester call wasn't correct ``tester().waitForView(withAccessibilityLabel: superHero.name)`` but the new one doesn't ensure the detail screen is open. Could we replace this one with a call to ensure the navbar shows the superhero name?

2020-03-10 10:17 UTC, pedrovgs commented
Is there any CI check configured for this repository?

2020-03-10 16:58 UTC, davideme commented on KataSuperHeroesTests/SuperHeroesViewControllerTests.swift
> -    }
There is not yet way to test UI elements yet. As elements like SwiftUI.List does not have properties to query them and is meant only as the definition. 
I tried using a library called [SwiftUI-Introspect](https://github.com/siteline/SwiftUI-Introspect) but the accessibility item does not match something that can be query with introspect.

2020-03-10 17:02 UTC, davideme commented on KataSuperHeroesTests/SuperHeroesViewControllerTests.swift
> +        tester().waitForAbsenceOfView(withAccessibilityLabel: "Superhero name")
I tried doing that, but that meant a lot of changes in the code. Definitely agreed would be a better solution, but the service locator needs to be changed and AppDelegate too.

As this is a variant of KataSuperHeroesiOS, didn't wanted to introduce that many changes.

2020-03-10 17:06 UTC, davideme commented
Set as public and added to Travis @pedrovgs

2020-03-11 07:08 UTC, pedrovgs approved these changes

2020-03-11 08:26 UTC, merged